language: ruby
rvm:
- 2.2
deploy:
  provider: heroku
  api_key:
    secure: UkVLyQfKpKNVbhq1+AfWdCOWl1jXvBHOZIj4Ml33zq2KVTlTVlft4s8maVtTG1uNHnDrZuGbCWVs/DD2aeV8qC+sVuowsQC5g5vxx+crUwCU5KQ9xLr8SKLrfyT7p8uFfu0CfgDEAg3b2vPD2syLMpbv+ah8a2Bfz9JP2oE40Wfz7L9RNmw9hAvXhtqulscE8EsjsBIDL0G5XoQ0pL4iw3pFvrcvB3/Y73r8c8zA54GO6v4K3kS9RyLztWfMc36909oAyYlCqXPqcr0bNnjmW9TFgSDhGPXrbppDQHAn0tOp+5ZO1l0c5JgyhY4yZFgxFdKet/J2EnqnRvRrlZ7hw5HhwCd/38ONZEqL+oBY0a4NXPZga3AaK9Aq+2XnvKfITS6JqDejPcDWA0sL2gVJKotopvpEFhKzgw6Gl7XWloOHJy8iaHSUTxshSbHm6CqlXnMemDlHdfNCvMnf46skeeK3JuxUm5pnrUjDoHbcstnzv8l6+3mJgxrEVaSxTljjMufmMHfmD6JVgKQAzOM7LoNoPVba7KQQqx0mc9L0lQaxsQH0W2EG/O5AVNsUNkdI28Al6uHH8sLloYN0nDJo4mzF1k1osPX2crZvyTJXXrVTiZtB3H+34dzO08ASqADhWyPMbrtJWMF/sjnQ7OaiISAr/Mw2tFj/9qiRYfxQhSI=
  app: trviad3  
