language: ruby
rvm:
- 2.2
deploy:
  provider: heroku
  api_key:
    secure: TUcG1e8HVsNAn8hOhSB3NZiKt7FEOfSyDdd3E027xfK4sIAPHqeYh7tX0YuQOAWYGwJRIzLN+/bG0zLv+i0iV5bBghj4JuCaOMg1yMMsdnU7BWVYzDvJDcMl+tNfctskEKPi0Vnd62Zt7I+FtXfmnBE6ls9BbIc8AkHvJaRPOtekl+ca/RI+pJl2RGDJfzb3OzUR5HBLGGW0OTarpC0I0Hp0C70/HwitLx81/p4MP0sTPaWYln4stesswe/pJ74iiSPJIPZW6AaB82fZVbK6mX/vuXAsyEuZP2fxx3vRR0cD/aNQCYvvM4V7cNyQY74673u5ymNxKTulJ5blCZlzqF4efCtY0KkPcYRzhTk9NArsLnQDhahri+U7lyANHG/c8HLx5PhfiEj+ljlau5oHcstLtw3tSBDvPcQOV4K/oHnCnb1flim9bkXVKo8PddWr6qurmygilSeksMXav74iyZQCZrlgGhfEuX99dEZijqx2x8+45oerT/Dg2Z8FMvAnPKnMtNentZhR8ZmBlegOAGFSoNfcfhtaw0AaIFDIQ/q+ubL3aHzjIDLElfMgIv2oedhVbfRlSYyAwkwiPWg1KwH9vV0eHrVqUeY2r4gEOnvAvg9xEMuTsW6ySDpJMkxgml/0U6LvXRHja/Q6LbxKI4irUo6g6vysSD8BluUVrSE=
  app: trviad3
